#!/usr/bin/env python3

"""
LLM-to-ROS Action Planning System
This module provides an interface to connect Large Language Models (LLMs) with 
ROS for generating action plans from natural language commands.
"""

import os
import json
import time
import threading
from typing import Dict, List, Optional, Any, Callable
from dataclasses import dataclass
from enum import Enum


class ActionType(Enum):
    """Enumeration of possible action types"""
    NAVIGATION = "navigation"
    MANIPULATION = "manipulation"
    PERCEPTION = "perception"
    COMMUNICATION = "communication"
    WAIT = "wait"
    CUSTOM = "custom"


@dataclass
class Action:
    """Represents a single action in an action plan"""
    action_type: ActionType
    parameters: Dict[str, Any]
    description: str = ""


@dataclass
class ActionPlan:
    """Represents a complete action plan generated by the LLM"""
    actions: List[Action]
    original_command: str
    confidence: float = 1.0
    generated_at: float = 0.0


class LLMActionPlanner:
    """
    A system that uses Large Language Models to generate action plans from 
    natural language commands and translates them to ROS-compatible actions.
    """
    
    def __init__(self, llm_provider: str = "openai", api_key: Optional[str] = None):
        """
        Initialize the LLM Action Planner
        
        Args:
            llm_provider: The LLM provider to use (e.g., 'openai', 'local')
            api_key: API key for the LLM service (if applicable)
        """
        self.llm_provider = llm_provider
        self.api_key = api_key or os.getenv("LLM_API_KEY")
        
        # Predefined locations in the environment
        self.locations = {
            'kitchen': {'x': 5.0, 'y': 3.0, 'theta': 0.0},
            'living room': {'x': 0.0, 'y': 0.0, 'theta': 0.0},
            'bedroom': {'x': -3.0, 'y': 4.0, 'theta': 0.0},
            'office': {'x': -2.0, 'y': -2.0, 'theta': 0.0},
            'table': {'x': 1.0, 'y': 2.0, 'theta': 0.0},
            'couch': {'x': 0.5, 'y': -1.0, 'theta': 0.0}
        }
        
        # Predefined objects in the environment
        self.objects = {
            'cup', 'book', 'ball', 'box', 'bottle', 'phone', 'red cup', 
            'blue ball', 'wooden box', 'glass bottle'
        }
        
        # Action execution callbacks
        self.action_callbacks: Dict[ActionType, Callable[[Action], bool]] = {}
        
        # Safety constraints
        self.safety_constraints = {
            'forbidden_locations': ['restricted_area', 'danger_zone'],
            'valid_objects': self.objects,
            'max_navigation_distance': 20.0,
        }
        
        self.get_logger_info(f"LLM Action Planner initialized (provider: {llm_provider})")

    def get_logger_info(self, message: str):
        """Print info message - in a real implementation this would use ROS logging"""
        print(f"[INFO] {message}")

    def get_logger_error(self, message: str):
        """Print error message - in a real implementation this would use ROS logging"""
        print(f"[ERROR] {message}")

    def set_action_callback(self, action_type: ActionType, callback: Callable[[Action], bool]):
        """
        Set a callback function for executing a specific type of action
        
        Args:
            action_type: The type of action to set a callback for
            callback: Function to call with the action to execute
        """
        self.action_callbacks[action_type] = callback

    def plan_action(self, command: str) -> Optional[ActionPlan]:
        """
        Generate an action plan for the given command using the LLM
        
        Args:
            command: Natural language command to plan for
            
        Returns:
            ActionPlan object or None if planning failed
        """
        try:
            self.get_logger_info(f"Planning action for command: '{command}'")
            
            # Generate structured plan using the LLM
            plan_data = self._call_llm_for_planning(command)
            
            if not plan_data:
                self.get_logger_error(f"Failed to generate plan for command: {command}")
                return None
            
            # Convert the plan data to ActionPlan object
            action_plan = self._convert_to_action_plan(command, plan_data)
            
            # Validate the plan against safety constraints
            if self._validate_plan(action_plan):
                self.get_logger_info(f"Generated valid plan with {len(action_plan.actions)} actions")
                return action_plan
            else:
                self.get_logger_error("Generated plan failed validation against safety constraints")
                return None
                
        except Exception as e:
            self.get_logger_error(f"Error planning action: {e}")
            return None

    def _call_llm_for_planning(self, command: str) -> Optional[Dict[str, Any]]:
        """
        Call the LLM to generate a structured action plan
        
        Args:
            command: Natural language command to plan for
            
        Returns:
            Dictionary with plan information or None if failed
        """
        # This is a simulation of calling an actual LLM API
        # In a real implementation, this would call the actual LLM
        
        # For demonstration, we'll implement rule-based parsing for common commands
        # In a real system, this would be replaced with actual LLM API calls
        command_lower = command.lower()
        
        if "go to" in command_lower or "move to" in command_lower:
            # Extract location
            for location in self.locations:
                if location in command_lower:
                    return {
                        "actions": [
                            {
                                "type": "navigation",
                                "parameters": {"location": location, **self.locations[location]},
                                "description": f"Navigate to {location}"
                            }
                        ]
                    }
        
        elif "pick up" in command_lower or "grab" in command_lower or "get" in command_lower:
            # Extract object
            for obj in self.objects:
                if obj in command_lower:
                    return {
                        "actions": [
                            {
                                "type": "navigation",
                                "parameters": {"location": "object_location", "x": 0.5, "y": 0.0},
                                "description": f"Navigate to {obj}"
                            },
                            {
                                "type": "manipulation",
                                "parameters": {"action": "pick_up", "object": obj},
                                "description": f"Pick up {obj}"
                            }
                        ]
                    }
        
        elif "put" in command_lower or "place" in command_lower or "move" in command_lower:
            # Handle placement commands
            for obj in self.objects:
                if obj in command_lower:
                    # Find destination
                    for location in self.locations:
                        if location in command_lower or f"to {location}" in command_lower:
                            return {
                                "actions": [
                                    {
                                        "type": "navigation",
                                        "parameters": {"location": location, **self.locations[location]},
                                        "description": f"Navigate to {location}"
                                    },
                                    {
                                        "type": "manipulation",
                                        "parameters": {"action": "place", "object": obj, "destination": location},
                                        "description": f"Place {obj} at {location}"
                                    }
                                ]
                            }
        
        else:
            # For other commands, return a mock plan based on keywords
            if any(word in command_lower for word in ["hello", "hi", "hey"]):
                return {
                    "actions": [
                        {
                            "type": "communication",
                            "parameters": {"message": "Hello! How can I assist you?"},
                            "description": "Greet the user"
                        }
                    ]
                }
        
        # If no pattern matched, return None
        return None

    def _convert_to_action_plan(self, original_command: str, plan_data: Dict[str, Any]) -> ActionPlan:
        """Convert plan data from LLM to ActionPlan object"""
        actions = []
        
        for action_data in plan_data.get("actions", []):
            action_type_str = action_data.get("type", "")
            try:
                action_type = ActionType(action_type_str)
            except ValueError:
                self.get_logger_info(f"Unknown action type '{action_type_str}', using CUSTOM")
                action_type = ActionType.CUSTOM
            
            action = Action(
                action_type=action_type,
                parameters=action_data.get("parameters", {}),
                description=action_data.get("description", "")
            )
            actions.append(action)
        
        return ActionPlan(
            actions=actions,
            original_command=original_command,
            confidence=plan_data.get("confidence", 0.8),  # Default confidence
            generated_at=time.time()
        )

    def _validate_plan(self, plan: ActionPlan) -> bool:
        """Validate that the action plan meets safety constraints"""
        for action in plan.actions:
            if not self._is_action_safe(action):
                return False
        return True

    def _is_action_safe(self, action: Action) -> bool:
        """Check if individual action is safe to execute"""
        # Check if action type is valid
        if action.action_type not in ActionType:
            return False

        params = action.parameters

        # Check location safety for navigation
        if action.action_type == ActionType.NAVIGATION:
            location = params.get('location')
            if location in self.safety_constraints['forbidden_locations']:
                return False

            # Check distance if coordinates provided
            if 'x' in params and 'y' in params:
                # For simplicity, we'll assume robot starts at (0, 0)
                distance = ((params['x'])**2 + (params['y'])**2)**0.5
                if distance > self.safety_constraints['max_navigation_distance']:
                    return False

        # Check object safety for manipulation
        elif action.action_type == ActionType.MANIPULATION:
            obj_name = params.get('object', '').lower()
            if obj_name not in self.safety_constraints['valid_objects']:
                return False

        return True

    def execute_plan(self, plan: ActionPlan) -> bool:
        """
        Execute the given action plan
        
        Args:
            plan: The action plan to execute
            
        Returns:
            True if all actions executed successfully, False otherwise
        """
        self.get_logger_info(f"Executing plan with {len(plan.actions)} actions")
        
        for i, action in enumerate(plan.actions):
            self.get_logger_info(f"Executing action {i+1}/{len(plan.actions)}: {action.description}")
            
            # Check if there's a callback for this action type
            if action.action_type in self.action_callbacks:
                try:
                    success = self.action_callbacks[action.action_type](action)
                    if not success:
                        self.get_logger_error(f"Action failed: {action.description}")
                        return False
                except Exception as e:
                    self.get_logger_error(f"Error executing action: {e}")
                    return False
            else:
                self.get_logger_info(f"No callback registered for action type {action.action_type}, skipping")
        
        self.get_logger_info("Plan executed successfully")
        return True

    def execute_command(self, command: str) -> bool:
        """
        Execute a natural language command end-to-end
        
        Args:
            command: Natural language command to execute
            
        Returns:
            True if command executed successfully, False otherwise
        """
        # Plan the action
        plan = self.plan_action(command)
        if not plan:
            return False
        
        # Execute the plan
        return self.execute_plan(plan)

    def get_location_pose(self, location_name: str) -> Optional[Dict[str, float]]:
        """Get the pose (x, y, theta) for a named location"""
        if location_name in self.locations:
            return self.locations[location_name]
        return None


# Example usage and testing
if __name__ == "__main__":
    def mock_navigation_callback(action: Action) -> bool:
        """Mock callback for navigation actions"""
        params = action.parameters
        if 'location' in params:
            location = params['location']
            pose = planner.get_location_pose(location)
            if pose:
                print(f"  Navigating to {location} at ({pose['x']}, {pose['y']})")
            else:
                print(f"  Navigating to coordinates ({params.get('x', 0)}, {params.get('y', 0)})")
        else:
            print("  Navigating to coordinates")
        return True  # Simulate success

    def mock_manipulation_callback(action: Action) -> bool:
        """Mock callback for manipulation actions"""
        params = action.parameters
        action_name = params.get('action', 'unknown')
        obj = params.get('object', 'unknown object')
        dest = params.get('destination', 'unknown')
        
        if action_name == 'pick_up':
            print(f"  Picking up {obj}")
        elif action_name == 'place':
            print(f"  Placing {obj} at {dest}")
        else:
            print(f"  Performing {action_name} on {obj}")
        return True  # Simulate success

    def mock_communication_callback(action: Action) -> bool:
        """Mock callback for communication actions"""
        params = action.parameters
        message = params.get('message', 'Hello!')
        print(f"  Communicating: {message}")
        return True  # Simulate success

    # Initialize the LLM Action Planner
    try:
        planner = LLMActionPlanner(llm_provider="rule_based_demo")
        
        # Register action callbacks
        planner.set_action_callback(ActionType.NAVIGATION, mock_navigation_callback)
        planner.set_action_callback(ActionType.MANIPULATION, mock_manipulation_callback)
        planner.set_action_callback(ActionType.COMMUNICATION, mock_communication_callback)
        
        # Test commands
        test_commands = [
            "Go to the kitchen",
            "Move to the living room", 
            "Pick up the red cup",
            "Grab the ball",
            "Put the book on the table",
            "Place the box in the bedroom",
            "Hello robot"
        ]
        
        print("LLM Action Planner ready. Testing commands:")
        print("="*50)
        
        for command in test_commands:
            print(f"\nCommand: '{command}'")
            success = planner.execute_command(command)
            status = "SUCCESS" if success else "FAILED"
            print(f"Status: {status}")
            print("-" * 30)
        
    except Exception as e:
        print(f"Error initializing LLM Action Planner: {e}")
        exit(1)